import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-poppins'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} bg-gray-500/100 dark:bg-grey-900 text-black dark:text-white overflow-x-hidden`}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          {children}
          {/*<Analytics />*/}
        </ThemeProvider>
      </body>
    </html>
  );
}
